packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build

overrides:
  deepmerge-ts@<8.0.0: 8.0.0
  mysql2@<3.22.0: 3.22.0

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  '@scarf/scarf': false
  protobufjs: true
