CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

ALTER TABLE "User"
  ADD COLUMN "role" "UserRole" NOT NULL DEFAULT 'USER';

ALTER TYPE "ExerciseReportStatus" RENAME VALUE 'OPEN' TO 'NEW';
ALTER TYPE "ExerciseReportStatus" RENAME VALUE 'RESOLVED' TO 'FIXED';
ALTER TYPE "ExerciseReportStatus" ADD VALUE 'IN_PROGRESS' BEFORE 'FIXED';

ALTER TABLE "ExerciseReport"
  ALTER COLUMN "status" SET DEFAULT 'NEW';
