import type { CourseLessonContentSeed, CourseSkillSeed } from '../module-one.js'
import type { LessonVocabularySeed } from './fi.olla.basics.js'
import { PLURAL_PARTITIVE_USAGE_SKILL_ID } from './fi.plural.partitive.usage.js'

export const PLURAL_LOCAL_CASES_SKILL_ID = 'grammar.fi.plural.local-cases'
export const PLURAL_LOCAL_INESSIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.inessive'
export const PLURAL_LOCAL_ELATIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.elative'
export const PLURAL_LOCAL_ILLATIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.illative'
export const PLURAL_LOCAL_ADESSIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.adessive'
export const PLURAL_LOCAL_ABLATIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.ablative'
export const PLURAL_LOCAL_ALLATIVE_SKILL_ID =
  'grammar.fi.plural.local-cases.allative'

export const pluralLocalCasesSkills: CourseSkillSeed[] = [
  {
    id: PLURAL_LOCAL_CASES_SKILL_ID,
    kind: 'GRAMMAR',
    name: { ru: 'Местные падежи во множественном числе' },
    description: {
      ru: 'Внутренняя и внешняя серии с показателем множественного числа -i-.',
    },
    prerequisiteSkillIds: [PLURAL_PARTITIVE_USAGE_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_INESSIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Где внутри: -issa/-issä' },
    description: {
      ru: 'Местонахождение внутри нескольких мест, групп или предметов: yrityksissä.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_ELATIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Откуда изнутри: -ista/-istä' },
    description: {
      ru: 'Движение или источник из нескольких мест и предметов: rasioista.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_ILLATIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Куда внутрь: множественный иллатив' },
    description: {
      ru: 'Направление внутрь нескольких мест или предметов: laitteisiin, koreihin.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_ADESSIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Где снаружи и у кого: -illa/-illä' },
    description: {
      ru: 'Положение на нескольких поверхностях, инструмент и обладание: näytöillä, oppilailla.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_ABLATIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Откуда снаружи и от кого: -ilta/-iltä' },
    description: {
      ru: 'Движение с нескольких поверхностей и получение от нескольких источников: näytöiltä, johtajilta.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
  {
    id: PLURAL_LOCAL_ALLATIVE_SKILL_ID,
    kind: 'SPECIFIC_SKILL',
    name: { ru: 'Куда снаружи и кому: -ille' },
    description: {
      ru: 'Направление на несколько поверхностей и передача нескольким получателям: penkeille, oppilaille.',
    },
    prerequisiteSkillIds: [PLURAL_LOCAL_CASES_SKILL_ID],
  },
]

export const pluralLocalCasesContent: CourseLessonContentSeed = {
  version: 1,
  sections: ['explanation', 'vocabulary', 'practice'],
  explanationScreens: [
    {
      id: 'plural-local-overview',
      title: { ru: 'Те же шесть падежей, теперь для нескольких предметов' },
      paragraphs: [
        {
          ru: 'Значения местных падежей не меняются: внутренняя серия отвечает на вопросы «где внутри, откуда изнутри, куда внутрь», а внешняя — «где на поверхности или у кого, откуда или от кого, куда или кому».',
        },
        {
          ru: 'Во множественном числе между основой и падежным окончанием появляется показатель -i-. Сравни talossa и taloissa, pöydällä и pöydillä.',
        },
      ],
      table: {
        headers: [
          { ru: 'Направление' },
          { ru: 'Внутренняя серия' },
          { ru: 'Внешняя серия' },
        ],
        rows: [
          [{ ru: 'где' }, { ru: '-issa/-issä' }, { ru: '-illa/-illä' }],
          [{ ru: 'откуда' }, { ru: '-ista/-istä' }, { ru: '-ilta/-iltä' }],
          [{ ru: 'куда' }, { ru: 'иллатив мн. ч.' }, { ru: '-ille' }],
        ],
      },
      examples: [
        {
          target: 'He asuvat kylissä.',
          source: { ru: 'Они живут в деревнях.' },
        },
        {
          target: 'Tavarat ovat tasoilla.',
          source: { ru: 'Вещи находятся на поверхностях.' },
        },
        {
          target: 'Annan tehtäviä oppilaille.',
          source: { ru: 'Я даю задания ученикам.' },
        },
      ],
    },
    {
      id: 'plural-internal-series',
      title: { ru: 'Внутренняя серия: -issa, -ista и направление внутрь' },
      paragraphs: [
        {
          ru: 'Форма -issa/-issä сообщает, что что-то находится внутри нескольких мест или предметов: tuotteet ovat pakkauksissa.',
        },
        {
          ru: 'Элатив -ista/-istä обозначает движение изнутри или источник: otan tuotteet pakkauksista. Иллатив направляет внутрь: panen tuotteet pakkauksiin.',
        },
      ],
      table: {
        headers: [
          { ru: 'Падеж' },
          { ru: 'Единственное число' },
          { ru: 'Множественное число' },
        ],
        rows: [
          [{ ru: 'инессив' }, { ru: 'talossa' }, { ru: 'taloissa' }],
          [{ ru: 'элатив' }, { ru: 'talosta' }, { ru: 'taloista' }],
          [{ ru: 'иллатив' }, { ru: 'taloon' }, { ru: 'taloihin' }],
        ],
      },
      examples: [
        {
          target: 'Yrityksissä on työntekijöitä.',
          source: { ru: 'В компаниях есть сотрудники.' },
        },
        {
          target: 'Otan omenat rasioista.',
          source: { ru: 'Я достаю яблоки из коробок.' },
        },
        {
          target: 'Tallennan tiedostot laitteisiin.',
          source: { ru: 'Я сохраняю файлы на устройства.' },
        },
      ],
    },
    {
      id: 'plural-external-series',
      title: { ru: 'Внешняя серия: -illa, -ilta, -ille' },
      paragraphs: [
        {
          ru: 'Адессив -illa/-illä показывает положение на нескольких поверхностях, средство действия или обладателя: tavarat ovat tasoilla, oppilailla on tehtäviä.',
        },
        {
          ru: 'Аблатив -ilta/-iltä означает движение с поверхности или источник от людей и организаций. Аллатив -ille передаёт движение на поверхность или получателя.',
        },
      ],
      table: {
        headers: [
          { ru: 'Падеж' },
          { ru: 'Единственное число' },
          { ru: 'Множественное число' },
        ],
        rows: [
          [{ ru: 'адессив' }, { ru: 'pöydällä' }, { ru: 'pöydillä' }],
          [{ ru: 'аблатив' }, { ru: 'pöydältä' }, { ru: 'pöydiltä' }],
          [{ ru: 'аллатив' }, { ru: 'pöydälle' }, { ru: 'pöydille' }],
        ],
      },
      examples: [
        {
          target: 'He istuvat penkeillä.',
          source: { ru: 'Они сидят на скамейках.' },
        },
        {
          target: 'Saan tietoa asiantuntijoilta.',
          source: { ru: 'Я получаю информацию от специалистов.' },
        },
        {
          target: 'Lähetän raportit johtajille.',
          source: { ru: 'Я отправлю отчёты руководителям.' },
        },
      ],
    },
    {
      id: 'plural-local-stems',
      title: { ru: 'Окончание присоединяется к множественной основе' },
      paragraphs: [
        {
          ru: 'Нельзя просто добавить -issa или -illa к словарной форме. Сначала нужна множественная основа: kylä → kylissä, purkki → purkeissa, yritys → yrityksissä.',
        },
        {
          ru: 'Знакомое чередование согласных сохраняется: purkki имеет слабую основу purke- в purkeissa, а laite — сильную основу laitte- в laitteissa.',
        },
      ],
      table: {
        headers: [
          { ru: 'Слово' },
          { ru: 'Множественная основа' },
          { ru: 'Пример' },
        ],
        rows: [
          [{ ru: 'kylä' }, { ru: 'kyl-i-' }, { ru: 'kylissä' }],
          [{ ru: 'purkki' }, { ru: 'purke-i-' }, { ru: 'purkeissa' }],
          [{ ru: 'laite' }, { ru: 'laitte-i-' }, { ru: 'laitteissa' }],
          [{ ru: 'yritys' }, { ru: 'yrityks-i-' }, { ru: 'yrityksissä' }],
        ],
      },
      examples: [
        {
          target: 'Maito on purkeissa.',
          source: { ru: 'Молоко находится в банках.' },
        },
        {
          target: 'Tiedostot ovat laitteissa.',
          source: { ru: 'Файлы находятся на устройствах.' },
        },
        {
          target: 'Opiskelijat ovat ryhmissä.',
          source: { ru: 'Студенты находятся в группах.' },
        },
      ],
    },
    {
      id: 'plural-illative-patterns',
      title: { ru: 'Иллатив множественного числа имеет несколько моделей' },
      paragraphs: [
        {
          ru: 'У направления внутрь нет одного общего окончания для всех слов. Сравни rasioihin, kyliin, laitteisiin и yrityksiin.',
        },
        {
          ru: 'Опирайся на готовую пару «где — куда»: rasioissa → rasioihin, kylissä → kyliin, laitteissa → laitteisiin. Так легче сохранить правильную основу.',
        },
      ],
      table: {
        headers: [{ ru: 'Слово' }, { ru: 'Где' }, { ru: 'Куда' }],
        rows: [
          [{ ru: 'rasia' }, { ru: 'rasioissa' }, { ru: 'rasioihin' }],
          [{ ru: 'kylä' }, { ru: 'kylissä' }, { ru: 'kyliin' }],
          [{ ru: 'laite' }, { ru: 'laitteissa' }, { ru: 'laitteisiin' }],
          [{ ru: 'yritys' }, { ru: 'yrityksissä' }, { ru: 'yrityksiin' }],
        ],
      },
      examples: [
        {
          target: 'Panen omenat koreihin.',
          source: { ru: 'Я кладу яблоки в корзины.' },
        },
        {
          target: 'He siirtyvät tiimeihin.',
          source: { ru: 'Они переходят в команды.' },
        },
        {
          target: 'Lähetämme hakemuksia organisaatioihin.',
          source: { ru: 'Мы отправляем заявления в организации.' },
        },
      ],
    },
    {
      id: 'plural-internal-external-choice',
      title: { ru: 'Выбор серии остаётся смысловым' },
      paragraphs: [
        {
          ru: 'Множественное число не меняет выбор серии. Yrityksissä означает «внутри компаний, в компаниях», а yrityksillä — «у компаний» в конструкции обладания.',
        },
        {
          ru: 'С людьми внешняя серия часто выражает обладание и передачу: oppilailla «у учеников», oppilailta «от учеников», oppilaille «ученикам».',
        },
      ],
      table: {
        headers: [{ ru: 'Форма' }, { ru: 'Значение' }, { ru: 'Пример' }],
        rows: [
          [
            { ru: 'yrityksissä' },
            { ru: 'в компаниях' },
            { ru: 'Työskentelen yrityksissä.' },
          ],
          [
            { ru: 'yrityksillä' },
            { ru: 'у компаний' },
            { ru: 'Yrityksillä on palveluja.' },
          ],
          [
            { ru: 'oppilailta' },
            { ru: 'от учеников' },
            { ru: 'Saan vastauksia oppilailta.' },
          ],
          [
            { ru: 'oppilaille' },
            { ru: 'ученикам' },
            { ru: 'Annan tehtäviä oppilaille.' },
          ],
        ],
      },
      examples: [
        {
          target: 'Yrityksillä on palveluja.',
          source: { ru: 'У компаний есть услуги.' },
        },
        {
          target: 'Saan vastauksia aikuisilta.',
          source: { ru: 'Я получаю ответы от взрослых.' },
        },
        {
          target: 'Kerron asian aikuisille.',
          source: { ru: 'Я рассказываю об этом взрослым.' },
        },
      ],
      callout: {
        ru: 'Сначала выбери внутреннюю или внешнюю серию по смыслу, затем направление «где — откуда — куда», и только после этого образуй множественную основу.',
      },
    },
  ],
}

type LocalSeries = 'internal' | 'external'

const nouns = [
  [
    'kylä',
    'деревня',
    'в деревнях',
    'internal',
    'kylän',
    'kylää',
    'kylät',
    'kyliä',
    'kylissä',
    'kylistä',
    'kyliin',
    'kylillä',
    'kyliltä',
    'kylille',
    'He asuvat kylissä.',
    'Они живут в деревнях.',
  ],
  [
    'alue',
    'район, область',
    'в районах',
    'external',
    'alueen',
    'aluetta',
    'alueet',
    'alueita',
    'alueissa',
    'alueista',
    'alueisiin',
    'alueilla',
    'alueilta',
    'alueille',
    'Alueilla on rakennuksia.',
    'В районах есть здания.',
  ],
  [
    'valtio',
    'государство',
    'в государствах',
    'internal',
    'valtion',
    'valtiota',
    'valtiot',
    'valtioita',
    'valtioissa',
    'valtioista',
    'valtioihin',
    'valtioilla',
    'valtioilta',
    'valtioille',
    'He tulevat valtioista.',
    'Они приезжают из разных государств.',
  ],
  [
    'yritys',
    'компания, предприятие',
    'в компаниях',
    'internal',
    'yrityksen',
    'yritystä',
    'yritykset',
    'yrityksiä',
    'yrityksissä',
    'yrityksistä',
    'yrityksiin',
    'yrityksillä',
    'yrityksiltä',
    'yrityksille',
    'Yrityksissä on työntekijöitä.',
    'В компаниях есть сотрудники.',
  ],
  [
    'organisaatio',
    'организация',
    'в организациях',
    'internal',
    'organisaation',
    'organisaatiota',
    'organisaatiot',
    'organisaatioita',
    'organisaatioissa',
    'organisaatioista',
    'organisaatioihin',
    'organisaatioilla',
    'organisaatioilta',
    'organisaatioille',
    'He työskentelevät organisaatioissa.',
    'Они работают в организациях.',
  ],
  [
    'yhdistys',
    'объединение, ассоциация',
    'в объединениях',
    'internal',
    'yhdistyksen',
    'yhdistystä',
    'yhdistykset',
    'yhdistyksiä',
    'yhdistyksissä',
    'yhdistyksistä',
    'yhdistyksiin',
    'yhdistyksillä',
    'yhdistyksiltä',
    'yhdistyksille',
    'Yhdistyksissä on ryhmiä.',
    'В объединениях есть группы.',
  ],
  [
    'ryhmä',
    'группа',
    'в группах',
    'internal',
    'ryhmän',
    'ryhmää',
    'ryhmät',
    'ryhmiä',
    'ryhmissä',
    'ryhmistä',
    'ryhmiin',
    'ryhmillä',
    'ryhmiltä',
    'ryhmille',
    'Opiskelijat ovat ryhmissä.',
    'Студенты находятся в группах.',
  ],
  [
    'joukkue',
    'команда',
    'в командах',
    'internal',
    'joukkueen',
    'joukkuetta',
    'joukkueet',
    'joukkueita',
    'joukkueissa',
    'joukkueista',
    'joukkueisiin',
    'joukkueilla',
    'joukkueilta',
    'joukkueille',
    'He pelaavat joukkueissa.',
    'Они играют в командах.',
  ],
  [
    'tiimi',
    'команда, рабочая группа',
    'в командах',
    'internal',
    'tiimin',
    'tiimiä',
    'tiimit',
    'tiimejä',
    'tiimeissä',
    'tiimeistä',
    'tiimeihin',
    'tiimeillä',
    'tiimeiltä',
    'tiimeille',
    'He siirtyvät tiimeihin.',
    'Они переходят в команды.',
  ],
  [
    'rasia',
    'коробка, футляр',
    'в коробках',
    'internal',
    'rasian',
    'rasiaa',
    'rasiat',
    'rasioita',
    'rasioissa',
    'rasioista',
    'rasioihin',
    'rasioilla',
    'rasioilta',
    'rasioille',
    'Otan omenat rasioista.',
    'Я достаю яблоки из коробок.',
  ],
  [
    'pussi',
    'пакет, мешок',
    'в пакетах',
    'internal',
    'pussin',
    'pussia',
    'pussit',
    'pusseja',
    'pusseissa',
    'pusseista',
    'pusseihin',
    'pusseilla',
    'pusseilta',
    'pusseille',
    'Tavarat ovat pusseissa.',
    'Вещи находятся в пакетах.',
  ],
  [
    'purkki',
    'банка',
    'в банках',
    'internal',
    'purkin',
    'purkkia',
    'purkit',
    'purkkeja',
    'purkeissa',
    'purkeista',
    'purkkeihin',
    'purkeilla',
    'purkeilta',
    'purkeille',
    'Maito on purkeissa.',
    'Молоко находится в банках.',
  ],
  [
    'kori',
    'корзина',
    'в корзинах',
    'internal',
    'korin',
    'koria',
    'korit',
    'koreja',
    'koreissa',
    'koreista',
    'koreihin',
    'koreilla',
    'koreilta',
    'koreille',
    'Omenat ovat koreissa.',
    'Яблоки находятся в корзинах.',
  ],
  [
    'pakkaus',
    'упаковка',
    'в упаковках',
    'internal',
    'pakkauksen',
    'pakkausta',
    'pakkaukset',
    'pakkauksia',
    'pakkauksissa',
    'pakkauksista',
    'pakkauksiin',
    'pakkauksilla',
    'pakkauksilta',
    'pakkauksille',
    'Tuotteet ovat pakkauksissa.',
    'Товары находятся в упаковках.',
  ],
  [
    'penkki',
    'скамейка',
    'на скамейках',
    'external',
    'penkin',
    'penkkiä',
    'penkit',
    'penkkejä',
    'penkeissä',
    'penkeistä',
    'penkkeihin',
    'penkeillä',
    'penkeiltä',
    'penkeille',
    'He istuvat penkeillä.',
    'Они сидят на скамейках.',
  ],
  [
    'sohva',
    'диван',
    'на диванах',
    'external',
    'sohvan',
    'sohvaa',
    'sohvat',
    'sohvia',
    'sohvissa',
    'sohvista',
    'sohviin',
    'sohvilla',
    'sohvilta',
    'sohville',
    'He nousevat sohvilta.',
    'Они встают с диванов.',
  ],
  [
    'taso',
    'уровень, поверхность',
    'на поверхностях',
    'external',
    'tason',
    'tasoa',
    'tasot',
    'tasoja',
    'tasoissa',
    'tasoista',
    'tasoihin',
    'tasoilla',
    'tasoilta',
    'tasoille',
    'Tavarat ovat tasoilla.',
    'Вещи находятся на поверхностях.',
  ],
  [
    'alusta',
    'основа, платформа',
    'на платформах',
    'external',
    'alustan',
    'alustaa',
    'alustat',
    'alustoja',
    'alustoissa',
    'alustoista',
    'alustoihin',
    'alustoilla',
    'alustoilta',
    'alustoille',
    'Kuvia on alustoilla.',
    'На платформах есть изображения.',
  ],
  [
    'näyttö',
    'экран, дисплей',
    'на экранах',
    'external',
    'näytön',
    'näyttöä',
    'näytöt',
    'näyttöjä',
    'näytöissä',
    'näytöistä',
    'näyttöihin',
    'näytöillä',
    'näytöiltä',
    'näytöille',
    'Kuvat ovat näytöillä.',
    'Изображения находятся на экранах.',
  ],
  [
    'sivu',
    'страница, сторона',
    'на страницах',
    'external',
    'sivun',
    'sivua',
    'sivut',
    'sivuja',
    'sivuissa',
    'sivuista',
    'sivuihin',
    'sivuilla',
    'sivuilta',
    'sivuille',
    'Luen uutisia sivuilta.',
    'Я читаю новости со страниц.',
  ],
  [
    'verkkosivu',
    'веб-страница',
    'на веб-страницах',
    'external',
    'verkkosivun',
    'verkkosivua',
    'verkkosivut',
    'verkkosivuja',
    'verkkosivuissa',
    'verkkosivuista',
    'verkkosivuihin',
    'verkkosivuilla',
    'verkkosivuilta',
    'verkkosivuille',
    'Tiedot ovat verkkosivuilla.',
    'Информация находится на веб-страницах.',
  ],
  [
    'laite',
    'устройство, прибор',
    'в устройствах',
    'internal',
    'laitteen',
    'laitetta',
    'laitteet',
    'laitteita',
    'laitteissa',
    'laitteista',
    'laitteisiin',
    'laitteilla',
    'laitteilta',
    'laitteille',
    'Tallennan tiedostot laitteisiin.',
    'Я сохраняю файлы на устройства.',
  ],
  [
    'oppilas',
    'ученик, ученица',
    'у учеников',
    'external',
    'oppilaan',
    'oppilasta',
    'oppilaat',
    'oppilaita',
    'oppilaissa',
    'oppilaista',
    'oppilaisiin',
    'oppilailla',
    'oppilailta',
    'oppilaille',
    'Annan tehtäviä oppilaille.',
    'Я даю задания ученикам.',
  ],
  [
    'aikuinen',
    'взрослый',
    'у взрослых',
    'external',
    'aikuisen',
    'aikuista',
    'aikuiset',
    'aikuisia',
    'aikuisissa',
    'aikuisista',
    'aikuisiin',
    'aikuisilla',
    'aikuisilta',
    'aikuisille',
    'Saan vastauksia aikuisilta.',
    'Я получаю ответы от взрослых.',
  ],
  [
    'asiantuntija',
    'специалист, эксперт',
    'у специалистов',
    'external',
    'asiantuntijan',
    'asiantuntijaa',
    'asiantuntijat',
    'asiantuntijoita',
    'asiantuntijoissa',
    'asiantuntijoista',
    'asiantuntijoihin',
    'asiantuntijoilla',
    'asiantuntijoilta',
    'asiantuntijoille',
    'Saan tietoa asiantuntijoilta.',
    'Я получаю информацию от специалистов.',
  ],
  [
    'johtaja',
    'руководитель, директор',
    'у руководителей',
    'external',
    'johtajan',
    'johtajaa',
    'johtajat',
    'johtajia',
    'johtajissa',
    'johtajista',
    'johtajiin',
    'johtajilla',
    'johtajilta',
    'johtajille',
    'Lähetän raportit johtajille.',
    'Я отправлю отчёты руководителям.',
  ],
] as const

export const pluralLocalCasesVocabulary: LessonVocabularySeed[] = nouns.map(
  (item, index) => nounVocabulary(item, index + 1),
)

function nounVocabulary(
  item: (typeof nouns)[number],
  position: number,
): LessonVocabularySeed {
  const [
    lemma,
    gloss,
    sourcePlural,
    localSeries,
    genitiveSingular,
    partitiveSingular,
    nominativePlural,
    partitivePlural,
    inessivePlural,
    elativePlural,
    illativePlural,
    adessivePlural,
    ablativePlural,
    allativePlural,
    exampleTarget,
    exampleSource,
  ] = item
  const serial = serialFor(position)
  const focusForm =
    (localSeries as LocalSeries) === 'internal'
      ? inessivePlural
      : adessivePlural

  return {
    ...identity(serial, lemma),
    lemma,
    partOfSpeech: 'noun',
    gloss,
    example: { target: exampleTarget, source: { ru: exampleSource } },
    semanticTypes: [
      'module-two',
      'plural-local-cases',
      `local-series:${localSeries}`,
    ],
    singular: lemma,
    plural: focusForm,
    sourceSingular: gloss,
    sourcePlural,
    forms: [
      form(serial, 'nominative-singular', lemma, {
        case: 'nominative',
        number: 'singular',
      }),
      form(serial, 'genitive-singular', genitiveSingular, {
        case: 'genitive',
        number: 'singular',
      }),
      form(serial, 'partitive-singular', partitiveSingular, {
        case: 'partitive',
        number: 'singular',
      }),
      form(serial, 'nominative-plural', nominativePlural, {
        case: 'nominative',
        number: 'plural',
      }),
      form(serial, 'partitive-plural', partitivePlural, {
        case: 'partitive',
        number: 'plural',
      }),
      form(serial, 'inessive-plural', inessivePlural, {
        case: 'inessive',
        number: 'plural',
      }),
      form(serial, 'elative-plural', elativePlural, {
        case: 'elative',
        number: 'plural',
      }),
      form(serial, 'illative-plural', illativePlural, {
        case: 'illative',
        number: 'plural',
      }),
      form(serial, 'adessive-plural', adessivePlural, {
        case: 'adessive',
        number: 'plural',
      }),
      form(serial, 'ablative-plural', ablativePlural, {
        case: 'ablative',
        number: 'plural',
      }),
      form(serial, 'allative-plural', allativePlural, {
        case: 'allative',
        number: 'plural',
      }),
    ],
  }
}

function identity(serial: string, lemma: string) {
  return {
    key: `m2-${serial.replace('.', '-')}`,
    itemId: `word.fi.m2.${serial}`,
    conceptId: `concept.fi.m2.${serial}`,
    lexicalEntryId: `lex.fi.${lemma}`,
  }
}

function serialFor(position: number) {
  return `06.${String(position).padStart(2, '0')}`
}

function form(
  serial: string,
  key: string,
  surface: string,
  features: Record<string, string>,
) {
  return { id: `form.fi.m2.${serial}.${key}`, surface, features }
}
